// Nguồn duy nhất cho đường dẫn trong app
export const routes = {
  home: '/feed',
  login: '/login',
  resetPassword: '/reset-password',
  feed: '/feed',
  challenges: '/challenges',
  challenge: (id: string, code?: string | null) => `/challenges/${encodeURIComponent(id)}${code ? `?code=${encodeURIComponent(code)}` : ''}`,
  newChallenge: '/challenges/new',
  run: '/run',
  clubs: '/clubs',
  club: (id: string) => `/clubs/${encodeURIComponent(id)}`,
  clubTab: (id: string, tab: 'chat' | 'challenges' | 'leaderboard' | 'members' | 'treasury' | 'settings' | 'photos' | 'hall' | 'shop' | 'exchange' | 'settings' | 'admin') => `/clubs/${encodeURIComponent(id)}/${tab}`,
  notifications: '/notifications',
  messages: '/messages',
  message: (userId: string) => `/messages/${encodeURIComponent(userId)}`,
  orgs: '/orgs',
  org: (id: string) => `/orgs/${encodeURIComponent(id)}`,
  orgCampaign: (orgId: string, id: string) => `/orgs/${encodeURIComponent(orgId)}/campaigns/${encodeURIComponent(id)}`,
  orgJoin: (code: string) => `/orgs/join/${encodeURIComponent(code)}`,
  enterprise: '/doanh-nghiep',
  plans: '/goi',
  me: '/me',
  settings: '/me/settings',
  wallet: '/wallet',
  plan: '/me/plan',
  insights: '/me/insights',
  shine: '/me/shine',
  vouchers: '/me/vouchers',
  invite: '/me/invite',
  market: '/market',
  marketMine: '/market/me',
  partner: (id: string) => `/market/${encodeURIComponent(id)}`,
  character: '/character',
  admin: '/admin',
  welcome: '/welcome',
  privacy: '/privacy',
  terms: '/terms',
  help: '/help',
  helpPage: (slug: string) => `/help/${encodeURIComponent(slug)}`,
  activities: '/activities',
  victory: '/victory',
  victoryCreate: (kind: string, ref: string, opts: { user?: string | null; pick?: boolean } = {}) =>
    `/victory/create?kind=${encodeURIComponent(kind)}&ref=${encodeURIComponent(ref)}${opts.user ? `&user=${encodeURIComponent(opts.user)}` : ''}${opts.pick ? '&pick=1' : ''}`,
  victoryVerify: (code: string) => `/v/${encodeURIComponent(code)}`,
  athlete: (id: string) => `/athletes/${encodeURIComponent(id)}`,
  activity: (id: string) => `/activities/${encodeURIComponent(id)}`,
  learn: '/learn',
  learnArticle: (slug: string) => `/learn/${encodeURIComponent(slug)}`,
  learnStudio: '/learn/studio',
  learnWrite: '/learn/write',
  nearby: '/nearby',
  nearbyConnections: '/nearby/connections',
  nearbyEvent: (id: string) => `/nearby/events/${encodeURIComponent(id)}`,
  races: '/races',
  race: (id: string) => `/races/${encodeURIComponent(id)}`,
} as const

/** Chỉ chấp nhận đường dẫn nội bộ cho tham số ?next= (chống open redirect) */
export function safeNext(next: string | null | undefined, fallback: string = routes.home) {
  if (!next || !next.startsWith('/') || next.startsWith('//') || next.startsWith('/\\')) return fallback
  return next
}
