// Cổng công khai của module game. Code ngoài module chỉ import từ '@/features/game'.
export { GameHub } from './components/GameHub'
export { RewardCascade } from './components/RewardCascade'
export { BadgeGrid } from './components/BadgeGrid'
export { WalletView } from './components/WalletView'
export { GiftButton } from './components/GiftButton'
export { GiftWall } from './components/GiftWall'
export { FormChip } from './components/FormChip'
export { useAchievements, useActivityRewards, useGiftWall, useMarkSeen } from './hooks/useGame'
export type { GameEvent } from './model/game'
export { ShineScreen } from './components/ShineScreen'
export { TopSupported } from './components/TopSupported'
